const MORPHOLOGIES_IN_ORDER = [
    'FIRST+MF+SINGULAR', 
    'FIRST+M+SINGULAR', 
    'FIRST+F+SINGULAR', 
    'SECOND+M+SINGULAR', 
    'SECOND+F+SINGULAR',
    'THIRD+M+SINGULAR',
    'THIRD+F+SINGULAR',
    'FIRST+MF+PLURAL',
    'FIRST+M+PLURAL',
    'FIRST+F+PLURAL',
    'THIRD+M+PLURAL',
    'THIRD+F+PLURAL',
    'SECOND+M+PLURAL',
    'SECOND+F+PLURAL'
];

export default MORPHOLOGIES_IN_ORDER;