export { default as HefilInflection } from './Hefil'
export { default as HitpaelInflection } from './Hitpael'
export { default as NifalInflection } from './Nifal'
export { default as PaalInflection } from './Paal'
export { default as PielInflection } from './Piel'
export { default as groupRulesByTense } from './groupRulesByTense'